sudo: required
services: 
    - docker 

before_install: 
    - docker build -t jvn2292/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true jvn2292/docker-react npm run test

deploy: 
    edge: true
    provider: elasticbeanstalk 
    region: "us-east-2"
    app: docker-react 
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-231425648061"
    bucket_path: "docker-react"
    on: 
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY